import Rx from "rxjs";
import HttpService from "../Http.service";

class SkillsService {
    static mock = [{
        key: "NPM",
        skill: 100,
        className: "devicon-npm-original-wordmark"
    }, {
        key: "Iconic",
        skill: 5,
        className: "devicon-ionic-original"
    }, {
        key: "Electron",
        skill: 5,
        className: "devicon-electron-original"
    }, {
        key: "Yarn",
        skill: 100,
        className: "devicon-yarn-plain"
    }, {
        key: "Handlebars/Mustache",
        skill: 100,
        className: "devicon-handlebars-plain"
    }, {
        key: "CouchDB",
        skill: 50,
        className: "devicon-couchdb-plain"
    }, {
        key: "Elm",
        skill: 0,
        className: "devicon-elm-plain"
    }, {
        key: "CakePHP",
        skill: 0,
        className: "devicon-cakephp-plain"
    }, {
        key: "Express",
        skill: 85,
        className: "devicon-express-original"
    }, {
        key: "IntelliJ",
        skill: 90,
        className: "devicon-intellij-plain"
    }, {
        key: "Pycharm",
        skill: 0,
        className: "devicon-pycharm-plain"
    }, {
        key: "Ruby Mine",
        skill: 0,
        className: "devicon-rubymine-plain"
    }, {
        key: "Webstorm",
        skill: 100,
        className: "webstorm-plain"
    }, {
        key: "Tomcat",
        skill: 70,
        className: "devicon-tomcat-line"
    }, {
        key: "VueJS",
        skill: 0,
        className: "devicon-vuejs-plain"
    }, {
        key: "Swift",
        skill: 0,
        className: "devicon-swift-plain"
    }, {
        key: "Webpack",
        skill: 80,
        className: "devicon-webpack-plain"
    }, {
        key: "Visual Studio",
        skill: 70,
        className: "devicon-visualstudio-plain"
    }, {
        key: "Slack",
        skill: 100,
        className: "devicon-slack-plain"
    }, {
        key: "TypeScript",
        skill: 100,
        className: "devicon-typescript-plain"
    }, {
        key: "Babel",
        skill: 90,
        className: "devicon-babel-plain"
    }, {
        key: "Mocha",
        skill: 90,
        className: "devicon-mocha-plain"
    }, {
        key: "Jasmine",
        skill: 100,
        className: "devicon-jasmine-plain"
    }, {
        key: "SSH",
        skill: 100,
        className: "devicon-ssh-plain"
    }, {
        key: "SourceTree",
        skill: 100,
        className: "devicon-sourcetree-plain"
    }, {
        key: "PHPStorm",
        skill: 0,
        className: "devicon-phpstorm-plain"
    }, {
        key: "Protractor",
        skill: 70,
        className: "devicon-protractor-plain"
    }, {
        key: "Gradle",
        skill: 50,
        className: "devicon-gradle-plain"
    }, {
        key: "Cucumber",
        skill: 70,
        className: "devicon-cucumber-plain"
    }, {
        key: "Gitlab",
        skill: 100,
        className: "devicon-gitlab-plain"
    }, {
        key: "Github",
        skill: 100,
        className: "devicon-github-plain"
    }, {
        key: "D3JS",
        skill: 10,
        className: "devicon-d3js-plain"
    }, {
        key: "Confluence",
        skill: 100,
        className: "devicon-confluence-plain"
    }, {
        key: "Bitbucket / Stash",
        skill: 100,
        className: "devicon-bitbucket-plain"
    }, {
        key: "Django",
        skill: 60,
        className: "devicon-django-plain"
    }, {
        key: "GIMP",
        skill: 85,
        className: "devicon-gimp-plain"
    }, {
        key: "C++",
        skill: 60,
        className: "devicon-cplusplus-plain"
    }, {
        key: "C#",
        skill: 60,
        className: "devicon-csharp-plain"
    }, {
        key: "C",
        skill: "C",
        className: "devicon-c-plain"
    }, {
        key: "NW / Node Webkit",
        skill: 0,
        className: "devicon-nodewebkit-plain"
    }, {
        key: "NGINX",
        skill: 90,
        className: "devicon-nginx-plain"
    }, {
        key: "Erlang",
        skill: 0,
        className: "devicon-erlang-plain"
    }, {
        key: "Apache",
        skill: 90,
        className: "devicon-apache-plain"
    }, {
        key: "Redis",
        skill: 0,
        className: "devicon-redis-plain"
    }, {
        key: "Meteor",
        skill: 0,
        className: "devicon-meteor-plain"
    }, {
        key: "Heroku",
        skill: 25,
        className: "devicon-heroku-plain"
    }, {
        key: "Go",
        skill: 0,
        className: "devicon-go-plain"
    }, {
        key: "Docker",
        skill: 80,
        className: "devicon-docker-plain"
    }, {
        key: "AWS",
        skill: 70,
        className: "devicon-amazonwebservices-plain"
    }, {
        key: "Android",
        skill: 60,
        className: "devicon-android-plain"
    }, {
        key: "Angular / AngularJS",
        skill: 100,
        className: "devicon-angularjs-plain"
    }, {
        key: "Apple/macOS",
        skill: 90,
        className: "devicon-apple-plain"
    }, {
        key: "Atom",
        skill: 0,
        className: "devicon-atom-plain"
    }, {
        key: "BackboneJS",
        skill: 90,
        className: "devicon-backbonejs-plain"
    }, {
        key: "Bootstrap",
        skill: 90,
        className: "devicon-bootstrap-plain"
    }, {
        key: "Bower",
        skill: 80,
        className: "devicon-bower-plain"
    }, {
        key: "CoffeeScript",
        skill: 80,
        className: "devicon-coffeescript-plain"
    }, {
        key: "CSS",
        skill: 90,
        className: "devicon-css3-plain"
    }, {
        key: ".NET",
        skill: 70,
        className: "devicon-dot-net-plain"
    }, {
        key: "Drupal",
        skill: 90,
        className: "devicon-drupal-plain"
    }, {
        key: "Git",
        skill: 90,
        className: "devicon-git-plain"
    }, {
        key: "Grunt",
        skill: 100,
        className: "devicon-grunt-plain"
    }, {
        key: "Gulp",
        skill: 100,
        className: "devicon-gulp-plain"
    }, {
        key: "HTML",
        skill: 100,
        className: "devicon-html5-plain"
    }, {
        key: "Illustrator",
        skill: 80,
        className: "devicon-illustrator-plain"
    }, {
        key: "Java",
        skill: 70,
        className: "devicon-java-plain"
    }, {
        key: "JavaScript / ES6+",
        skill: 100,
        className: "devicon-javascript-plain"
    }, {
        key: "jQuery",
        skill: 90,
        className: "devicon-jquery-plain"
    }, {
        key: "KrakenJS",
        skill: 0,
        className: "devicon-krakenjs-plain"
    }, {
        key: "LESS",
        skill: 100,
        className: "devicon-less-plain-wordmark"
    }, {
        key: "Linux",
        skill: 90,
        className: "devicon-linux-plain"
    }, {
        key: "MongoDB",
        skill: 80,
        className: "devicon-mongodb-plain"
    }, {
        key: "MySQL",
        skill: 90,
        className: "devicon-mysql-plain"
    }, {
        key: "NodeJS",
        skill: 95,
        className: "devicon-nodejs-plain"
    }, {
        key: "Oracle",
        skill: 70,
        className: "devicon-oracle-plain"
    }, {
        key: "Photoshop",
        skill: 100,
        className: "devicon-photoshop-plain"
    }, {
        key: "PHP",
        skill: 85,
        className: "devicon-php-plain"
    }, {
        key: "PostgreSQL",
        skill: 75,
        className: "devicon-postgresql-plain"
    }, {
        key: "Python",
        skill: 75,
        className: "devicon-python-plain"
    }, {
        key: "Ruby on Rails",
        skill: 25,
        className: "devicon-rails-plain"
    }, {
        key: "React",
        skill: 90,
        className: "devicon-react-plain"
    }, {
        key: "Ruby",
        skill: 25,
        className: "devicon-ruby-plain"
    }, {
        key: "SASS / SCSS",
        skill: 100,
        className: "devicon-sass-plain"
    }, {
        key: "Sequelize",
        skill: 0,
        className: "devicon-sequelize-plain"
    }, {
        key: "Travis",
        skill: 85,
        className: "devicon-travis-plain"
    }, {
        key: "VIM",
        skill: 85,
        className: "devicon-vim-plain"
    }, {
        key: "Windows",
        skill: 100,
        className: "devicon-windows8-plain"
    }, {
        key: "Wordpress",
        skill: 60,
        className: "devicon-wordpress-plain"
    }];

    static subject = new Rx.BehaviorSubject({
        skills: []
    });

    static get() {
        // return HttpService.get("/skills").then((response) => {
        //     SkillsService.subject.next(response);
        // });

        setTimeout(() => {
            SkillsService.subject.next({
                skills: SkillsService.mock
            });
        }, 750);
    }

    static subscribe(context) {
        return SkillsService.subject.subscribe((skills) => {
            context.setState(skills);
        });
    }
}

export default SkillsService;